sqlplus -s / as sysdba << EOF
    CREATE USER TOGDATA IDENTIFIED BY "${ORACLE_PASSWORD}";
    CREATE USER MLA IDENTIFIED BY "${ORACLE_PASSWORD}";
    CREATE USER LIQUIBASEADMIN IDENTIFIED BY "${ORACLE_PASSWORD}";

    GRANT CREATE SESSION TO TOGDATA;
    GRANT CREATE SESSION TO MLA;
    GRANT CREATE SESSION TO LIQUIBASEADMIN;
    GRANT DBA TO LIQUIBASEADMIN;

    commit;
EOF
